# 数据源配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 主库数据源
      master:
        url: jdbc:mysql://127.0.0.1:3306/forum_20240830?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
        password: '08191853'
      # 从库数据源
      slave:
        # 从数据源开关/默认关闭
        enabled: false
        url:
        username:
        password:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置连接超时时间
      connectTimeout: 30000
      # 配置网络超时时间
      socketTimeout: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: forum
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  # redis 配置
  redis:
    # 地址
    host: 192.168.150.101
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码
    password: '08191853'
    # 连接超时时间
    timeout: 600s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

#阿里云短信配置
aliyun:
  accessKeyID: LTAI5tKgLb73e2C1hzGJTYUF
  accessKeySecret: ia45nFVgfb8JZtBzurauCriLHe4re4
  signName: cj-cds
  templateCode: SMS_xxxxxxxxxxx

#邮箱相关配置
email:
  #发件人邮箱账号
  code: xxxxx@qq.com
  #发件人邮箱授权码
  passWord: xxxxxxxxxxxxxxx
  #发件邮箱主机 qq:smtp.qq.com, 163:host, 阿里：smtp.**.com
  host: smtp.qq.com
  #发件邮箱端口
  port: 465

file:
  #web/移动端上传文件保存目录
  uploadUrl: /home/forum/upload/avatar
  #Web/移动端上传文件外网访问目录
  showUrl: http://www.xxx.com/forum/upload/avatar                                                                                     forum/avatar